global using Microsoft.AspNetCore.OData;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OData.Edm;
global using Microsoft.OData.ModelBuilder;
global using ODataDemo.Context;
global using ODataDemo.Models;
global using ODataDemo.Service;
global using Microsoft.Net.Http.Headers;
global using Microsoft.OpenApi.Models;
global using static ODataDemo.Helpers.Enums.Enums;
global using System.Reflection;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.OData.Query;
global using ODataDemo.DTOs;
global using ODataDemo.DTOs.ResponseDTOs;
global using ODataDemo.HelpersDTOs;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text.Json.Serialization;
global using ODataDemo.Helpers.GenericSearchFilter;
global using ODataDemo.Helpers.GenericSort;
global using ODataDemo.Helpers.ODataConfiguration;

